# Generated by Django 3.0.6 on 2020-05-10 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'difficulty',
                'verbose_name_plural': 'difficulties',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=90)),
                ('class_description', models.CharField(max_length=255)),
                ('class_spec', models.CharField(max_length=55)),
                ('class_race', models.CharField(max_length=55)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boss_name', models.CharField(max_length=90)),
                ('boss_description', models.CharField(max_length=255)),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Difficulty')),
            ],
            options={
                'verbose_name': 'boss',
                'verbose_name_plural': 'bosses',
            },
        ),
    ]
