# Generated by Django 3.0.6 on 2020-05-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=90)),
                ('player_description', models.CharField(max_length=255)),
                ('player_spec', models.CharField(max_length=55)),
                ('player_race', models.CharField(max_length=55)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Class')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Role')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
