# Generated by Django 3.0.6 on 2020-05-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='boss_description',
            field=models.CharField(max_length=500),
        ),
    ]
